### ISSUE TITLE
High #Games problem (different than already known)

### ISSUE THREAD

**Issue by izhzz** [Mtihc/bustabit-script-simulator#5]
Hi, I really enjoy testing your simulator. I know the problem with high number of games (1 million+) is already known and I am eagerly waiting for a fix (maybe a precompiled list which you just feed it like suggested), but I have a different problem with one of the scripts I'm testing.

With the base hash (7edbd07968e771f205a4e2b67701c2f6993437db0c557160ba79ee70ea6d10c6) it can run 1 million games without busting, but If I go higher like 2 million it busts at game number ~35k. Sorry for asking but why is that? Shouldn't the bust happen only after the 1 million passed games (because the 1 million run sample didn't busted)? I thought the # of games are derived from the base hash so it should be the same list until 1 million right?

Hope I'm not as confusing as it sounds. Just a basic question about the logic. Best wishes!

Edit:
I checked the hashes manually and the specific "bust"-game (around 35k) which occures when going higher numbers (+200k/+2million games at certain script settings) is not going to go bust if I skip the first 34k games (insert starting hash of game 34,000) and let it run past the bust-game around number ~35k. So it might be that the simulator messes up if the number of games are too high, correct?

Right now I let my system run to get the hashes manually from the jsfiddler verification tool, if I have a good amount of game hashes I am happy to share the hashes in a list here, starting from your base hash (7edbd07968e771f205a4e2b67701c2f6993437db0c557160ba79ee70ea6d10c6).

**Comment by Mtihc** [comment]
Sorry for the extremely late response. 

You said...

> With the base hash (7edbd07968e771f205a4e2b67701c2f6993437db0c557160ba79ee70ea6d10c6) it can run 1 million games without busting, but If I go higher like 2 million it busts at game number ~35k. Sorry for asking but why is that? Shouldn't the bust happen only after the 1 million passed games (because the 1 million run sample didn't busted)? I thought the # of games are derived from the base hash so it should be the same list until 1 million right?

The game results are calculated backwards. So your input hash is always **the last** game. (**not the first** game)
So if you set the **Games #** to 1 million, you'll start way back in time. The simulator starts playing at minus 1 million games. And when it eventually reaches the 1 millionth game you'll find your input hash.
But if you set the **Games #** to 2 million, you'll start _even more way back in time_ (with a different hash). The simulator starts playing at minus 2 million games. The first ~35k games will be totally different from before!

I guess you had an unlucky streak. The house always wins, eventually.

The important thing to remember is that even if you use the **same input hash**, you'll have a **different starting hash**, depending on the **Games #** that you choose. Because the game results are calculated backwards. 

I believe this should clear up your confusion and answer your questions.
